image: maven:3.6.0

Maven_Build:
  stage: build
  script: mvn compile -e

Test:
  image: maven:3.6.0-jdk-10
  stage: test
  script: mvn clean test -e
  allow_failure: true

Client_Checkstyle:
  stage: test
  script:
    - mvn checkstyle:checkstyle
    - cat target/checkstyle-result.xml
    - cat modules/Server/target/checkstyle-result.xml
  allow_failure: true
  
  Server_Checkstyle:
   stage: test
   script:
    - mvn checkstyle:checkstyle
    - cat modules/Server/target/checkstyle-result.xml